// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6SpAktQQCYnIeeGvKP0QFEI-zYi_v__U',
    appId: '1:492565763607:web:6f9fe41c0647ae39e9ae52',
    messagingSenderId: '492565763607',
    projectId: 'acikartirmauygulamasi',
    authDomain: 'acikartirmauygulamasi.firebaseapp.com',
    storageBucket: 'acikartirmauygulamasi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKzF1a7HhNHFTRoflMNTWYXc9HR1iGMuo',
    appId: '1:492565763607:android:9360576e84961d37e9ae52',
    messagingSenderId: '492565763607',
    projectId: 'acikartirmauygulamasi',
    storageBucket: 'acikartirmauygulamasi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxq3ICCLvfh72ImPgT7JGCepcoOKsOlqk',
    appId: '1:492565763607:ios:917eda22ddd63b25e9ae52',
    messagingSenderId: '492565763607',
    projectId: 'acikartirmauygulamasi',
    storageBucket: 'acikartirmauygulamasi.appspot.com',
    iosBundleId: 'com.example.saattim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxq3ICCLvfh72ImPgT7JGCepcoOKsOlqk',
    appId: '1:492565763607:ios:37eeb30775b12ebce9ae52',
    messagingSenderId: '492565763607',
    projectId: 'acikartirmauygulamasi',
    storageBucket: 'acikartirmauygulamasi.appspot.com',
    iosBundleId: 'com.example.saattim.RunnerTests',
  );
}
